[tool.poetry]
name = "carplate"
version = "1"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
ultralytics = "^8.2.45"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
